INSERT INTO inventario_farmacia (nombre_medicamento, fecha_caducidad, cantidad_medicamento, precio_medicamento)
VALUES ('Paracetamol 500mg', '2027-05-15', 50, 5);

INSERT INTO inventario_farmacia (nombre_medicamento, fecha_caducidad, cantidad_medicamento, precio_medicamento)
VALUES ('Ibuprofeno 400mg', '2026-12-01', 30, 8);

INSERT INTO inventario_farmacia (nombre_medicamento, fecha_caducidad, cantidad_medicamento, precio_medicamento)
VALUES ('Amoxicilina 875mg', '2028-02-20', 15, 25);